-- noinspection SqlNoDataSourceInspectionForFile

CREATE TABLE TRAIN_MOVEMENTS (
                                     `msg_key` STRING NOT NULL,
                                     `msg_queue_timestamp` TIMESTAMP_LTZ(3),
                                     `msg_type` STRING,
                                     `original_data_source` STRING,
                                     `source_system_id` STRING,
                                     `actual_timestamp` TIMESTAMP_LTZ(3),
                                     `auto_expected` STRING,
                                     `correction_ind` STRING,
                                     `delay_monitoring_point` STRING,
                                     `direction_ind` STRING,
                                     `division_code` STRING,
                                     `event_source` STRING,
                                     `event_type` STRING,
                                     `gbtt_timestamp` TIMESTAMP_LTZ(3),
                                     `late_ind` INT,
                                     `loc_stanox` STRING,
                                     `mvt_description` STRING,
                                     `mvt_lat_lon` ROW<`lat` DOUBLE, `lon` DOUBLE>,
                                     `next_report_run_time` STRING,
                                     `next_report_stanox` STRING,
                                     `offroute_ind` STRING,
                                     `planned_event_type` STRING,
                                     `planned_timestamp` TIMESTAMP_LTZ(3),
                                     `platform` STRING,
                                     `reporting_stanox` STRING,
                                     `route` STRING,
                                     `timetable_variation` STRING,
                                     `toc_id` STRING,
                                     `toc` STRING,
                                     `train_id` STRING,
                                     `train_service_code` STRING,
                                     `train_terminated` STRING,
                                     `variation_status` STRING,
                                     `variation` STRING,
                                     `schedule_source` STRING,
                                     `tp_origin_timestamp` DATE,
                                     `schedule_type` STRING,
                                     `creation_timestamp` TIMESTAMP_LTZ(3),
                                     `origin_dep_timestamp` TIMESTAMP_LTZ(3),
                                     `d1266_record_number` STRING,
                                     `train_service_code_02` STRING,
                                     `sched_origin_stanox` STRING,
                                     `train_uid` STRING,
                                     `train_call_mode` STRING,
                                     `tp_origin_stanox` STRING,
                                     `schedule_wtt_id` STRING,
                                     `train_call_type` STRING,
                                     `schedule_end_date` DATE,
                                     `schedule_key` STRING NOT NULL,
                                     `sched_origin_desc` STRING,
                                     `schedule_num_stops` INT,
                                     `train_status` STRING,
                                     `power_type` STRING,
                                     `seating_classes` STRING,
                                     `reservations` STRING,
                                     `sleeping_accomodation` STRING,
                                     `train_category` STRING,
                                     `origin_tiploc_code` STRING,
                                     `origin_description` STRING,
                                     `origin_lat_lon` ROW<`lat` DOUBLE, `lon` DOUBLE>,
                                     `origin_public_departure_time` STRING,
                                     `origin_platform` STRING,
                                     `destination_tiploc_code` STRING,
                                     `destination_description` STRING,
                                     `destination_lat_lon` ROW<`lat` DOUBLE, `lon` DOUBLE>,
                                     `destination_public_arrival_time` STRING,
                                     `destination_platform` STRING
)
DISTRIBUTED INTO 1 BUCKETS
WITH (
    'changelog.mode' = 'append',
    'kafka.cleanup-policy' = 'delete',
    'kafka.retention.time' = '7 days',
    'kafka.consumer.isolation-level' = 'read-uncommitted'
    );
