-- noinspection SqlNoDataSourceInspectionForFile

CREATE TABLE TRAIN_REINSTATEMENTS (
                                      msg_queue_timestamp      TIMESTAMP_LTZ(3),
                                      msg_type                 STRING,
                                      original_data_source     STRING,
                                      source_system_id         STRING,
                                      train_file_address       STRING,
                                      train_service_code       STRING,
                                      orig_loc_stanox          STRING,
                                      toc_id                   STRING,
                                      toc                      STRING,
                                      dep_timestamp            TIMESTAMP_LTZ(3),
                                      loc_stanox               STRING,
                                      reinstatement_timestamp  TIMESTAMP_LTZ(3),
                                      train_id                 STRING,
                                      orig_loc_timestamp       TIMESTAMP_LTZ(3),
                                      canx_type                STRING,
                                      cancellation_location    STRING,
                                      cancellation_lat_lon     ROW(lat double, lon double),
                                      schedule_source          STRING,
                                      tp_origin_timestamp      DATE,
                                      schedule_type            STRING,
                                      creation_timestamp       TIMESTAMP_LTZ(3),
                                      origin_dep_timestamp     TIMESTAMP_LTZ(3),
                                      d1266_record_number      STRING,
                                      train_service_code_02    STRING,
                                      sched_origin_stanox      STRING,
                                      train_uid                STRING,
                                      train_call_mode          STRING,
                                      tp_origin_stanox         STRING,
                                      schedule_wtt_id          STRING,
                                      train_call_type          STRING,
                                      schedule_end_date        DATE,
                                      schedule_key             STRING,
                                      sched_origin_desc        STRING,
                                      schedule_num_stops       INTEGER,
                                      train_status             STRING,
                                      power_type               STRING,
                                      seating_classes          STRING,
                                      reservations             STRING,
                                      sleeping_accomodation    STRING,
                                      train_category           STRING,
                                      origin_tiploc_code       STRING,
                                      origin_description       STRING,
                                      origin_lat_lon           ROW(lat double, lon double),
                                      origin_public_departure_time STRING,
                                      origin_platform          STRING,
                                      destination_tiploc_code  STRING,
                                      destination_description  STRING,
                                      destination_lat_lon      ROW(lat double, lon double),
                                      destination_public_arrival_time STRING,
                                      destination_platform     STRING
)
DISTRIBUTED INTO 1 BUCKETS;
